// samples/angular-sixteen/src/app/app.component.ts
import { Component } from '@angular/core';
//You can import all the components like this
import '@collin/lit-components';

//The library also exports the types for the components
import { NJC_COMBOBOX_OPTION } from '@collin/lit-components/dist/types';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    title = 'angular-sixteen';
    options: NJC_COMBOBOX_OPTION[] = [
        {
            label: 'Option 1',
            value: '1'
        },
        {
            label: 'Option 2',
            value: '2'
        },
        {
            label: 'Option 3',
            value: '3'
        }
    ];
}

<router-outlet></router-outlet>
<div>
  SLDS Button
</div>
<nsc-button variant="brand">A SLDS Button</nsc-button>

<div>
  Gator Button
</div>
<ngc-button>A Gator Button</ngc-button>

<div>
  SLDS Combobox
</div>
<nsc-combobox
  label="SLDS Combobox"
  [options]="options"
></nsc-combobox>

// samples/react-next/src/app/page.tsx
'use client'
import { NJC_COMBOBOX_OPTION } from "@collin/lit-components";
import { useEffect, useRef } from "react";
import '@collin/lit-components';

export default function Home() {
    let options: NJC_COMBOBOX_OPTION[] = [
        {
            label: 'Option 1',
            value: '1'
        },
        {
            label: 'Option 2',
            value: '2'
        },
        {
            label: 'Option 3',
            value: '3'
        }
    ];

    const comboboxRef = useRef(null);

    useEffect(() => {
        if (comboboxRef.current) {
            comboboxRef.current.options = options;
        }
    }, [options]);

    return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24 dark:bg-slate-800">
            <div>
                SLDS Button
            </div>

            <nsc-button variant="brand">A SLDS Button</nsc-button>

            <div>
                Gator Button
            </div>
            <ngc-button>A Gator Button</ngc-button>
        </main>
    );
}
